missing_values:
  title: "drop_row"
  summary: "drop_row"
  content: "drop_row"
  links: "drop_row"
  url: "drop_row

# Define the rules for validating the data.
validation_rules:
  required_columns: ["title", "summary", "content", "links", "url"]
regex_patterns:
  url: "^(https?://)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([/\\w \\.-]*)*/?$"

# There are no date fields in this dataset.
date_columns: []

# Specify which columns should undergo text cleaning (e.g., trimming, lowercasing).
text_columns:
  - title
  - summary
  - content
  - links
  - url

# Outlier handling is generally not applicable for textual data.
outlier_handling:
  method: "none"
  threshold: 0.05

# Feature engineering: if the dataset doesn't include date or numeric interactions,
# leave these empty.
feature_engineering:
  date_features: []
  interactions: []
