missing_values:
  title: "drop_row"
  summary: "drop_row"
  content: "drop_row"
  links: "drop_row"
  url: "drop_row


validation_rules:
  required_columns: ["title", "summary", "content", "links", "url"]
regex_patterns:
  url: "^(https?://)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([/\\w \\.-]*)*/?$"

# Define the rules for handling dates.
date_columns: []

# Define the rules for handling text data.
text_columns:
  - title
  - summary
  - content
  - links
  - url

# Define the rules for handling outliers.
outlier_handling:
  method: "none"
  threshold: 0.05

# Define the rules for feature engineering.
feature_engineering:
  date_features: []
  interactions: []
