missing_values:
  age: "median"
  salary: "mean"
  department: "mode"
  start_date: "drop_column"

validation_rules:
  required_columns: ["employee_id", "hire_date"]
  value_ranges:
    age:
      min: 18
      max: 65
    salary:
      min: 30000
  regex_patterns:
    email: "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"

date_columns:
  - hire_date
  - termination_date

text_columns:
  - name
  - address

outlier_handling:
  method: "winsorize"
  threshold: 0.05

feature_engineering:
  date_features:
    - column: hire_date
      features: ["year", "month", "day_of_week"]
  interactions:
    - columns: ["age", "salary"]
      operation: "multiply"